@extends('layouts.app')

@section('content')
  <div>
     <h3> LaraAppointment GitHub here => </h3>
     <p>https://github.com/LaravelDaily/LaraAppointments-QuickAdminPanel</p>  
	 <br>
	 <ul>
	     <li><p> <b> My info </b> submenu is added via /partials/sidebar.blade.php </p></li>
	     <li><p> <b> Generated by..with QuickAdmin </b> is in /partials/header.blade.php </p> </li>
	 </ul>
  </div>	 
@stop

@section('javascript')
    
@endsection